### ISSUE TITLE
Failed to fetch plugin https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git via registry

### ISSUE THREAD

**Issue by royibernthal** [ionic-team/cordova-plugin-wkwebview-engine#154]
**cmd**

> ionic cordova plugin add https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git --save
> ✖ Running command - failed!
> 
> [ERROR] Cordova encountered an error.
>         You may get more insight by running the Cordova command above directly.
> 
> [ERROR] An error occurred while running cordova plugin add
>         https://github.com/ionic-team/cordova-plugin-wkwebview-engine... (exit code 1):
> 
>         Error: Failed to fetch plugin https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git via registry.
>         Probably this is either a connection problem, or plugin spec is incorrect.
>         Check your connection and plugin name/version/URL.
>         Error: cmd: Command failed with exit code 1 Error output:
>         npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
>         npm WARN addRemoteGit
>         npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
>         npm WARN addRemoteGit     at emitTwo (events.js:106:13)
>         npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
>         npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
>         npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
>         npm WARN addRemoteGit  git+https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git resetting remote
>         C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322
>         because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
>         npm WARN addRemoteGit
>         npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
>         npm WARN addRemoteGit     at emitTwo (events.js:106:13)
>         npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
>         npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
>         npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
>         npm WARN addRemoteGit   killed: false,
>         npm WARN addRemoteGit   code: 1,
>         npm WARN addRemoteGit   signal: null,
>         npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
>         npm ERR! git clone --template=C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
>         https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git
>         C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322:
>         Cloning into bare repository
>         'C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322'...
>         npm ERR! git clone --template=C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
>         https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git
>         C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322:
>         fatal: Unable to find remote helper for 'https'
>         npm ERR! Windows_NT 10.0.14393
>         npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program
>         Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
>         "https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git" "--save"
>         npm ERR! node v6.9.5
>         npm ERR! npm  v3.10.10
>         npm ERR! code 128
> 
>         npm ERR! Command failed: git -c core.longpaths=true clone
>         --template=C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
>         https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git
>         C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322
>         npm ERR! Cloning into bare repository
>         'C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322'...
>         npm ERR! fatal: Unable to find remote helper for 'https'
>         npm ERR!
>         npm ERR!
>         npm ERR! If you need help, you may report this error at:
>         npm ERR!     <https://github.com/npm/npm/issues>
> 
>         npm ERR! Please include the following file with any support request:
>         npm ERR!     D:\Projects\trt\client\node_modules\npm-debug.log

**npm-debug.log**

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'install',
> 1 verbose cli   'https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git',
> 1 verbose cli   '--save' ]
> 2 info using npm@3.10.10
> 3 info using node@v6.9.5
> 4 silly loadCurrentTree Starting
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 silly fetchPackageMetaData https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git
> 8 silly fetchOtherPackageData https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git
> 9 silly cache add args [ 'https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git',
> 9 silly cache add   null ]
> 10 verbose cache add spec https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git
> 11 silly cache add parsed spec Result {
> 11 silly cache add   raw: 'https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git',
> 11 silly cache add   scope: null,
> 11 silly cache add   escapedName: null,
> 11 silly cache add   name: null,
> 11 silly cache add   rawSpec: 'https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git',
> 11 silly cache add   spec: 'git+https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git',
> 11 silly cache add   type: 'hosted',
> 11 silly cache add   hosted:
> 11 silly cache add    { type: 'github',
> 11 silly cache add      ssh: 'git@github.com:ionic-team/cordova-plugin-wkwebview-engine.git',
> 11 silly cache add      sshUrl: 'git+ssh://git@github.com/ionic-team/cordova-plugin-wkwebview-engine.git',
> 11 silly cache add      httpsUrl: 'git+https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git',
> 11 silly cache add      gitUrl: 'git://github.com/ionic-team/cordova-plugin-wkwebview-engine.git',
> 11 silly cache add      shortcut: 'github:ionic-team/cordova-plugin-wkwebview-engine',
> 11 silly cache add      directUrl: 'https://raw.githubusercontent.com/ionic-team/cordova-plugin-wkwebview-engine/master/package.json' } }
> 12 verbose addRemoteGit caching https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git
> 13 verbose addRemoteGit git+https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git is a repository hosted by github
> 14 silly tryClone cloning git+https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git via git+https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git
> 15 verbose tryClone git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322 not in flight; caching
> 16 verbose correctMkdir C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
> 17 info git [ 'config', '--get', 'remote.origin.url' ]
> 18 warn addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> 18 warn addRemoteGit
> 18 warn addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
> 18 warn addRemoteGit     at emitTwo (events.js:106:13)
> 18 warn addRemoteGit     at ChildProcess.emit (events.js:191:7)
> 18 warn addRemoteGit     at maybeClose (internal/child_process.js:877:16)
> 18 warn addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 18 warn addRemoteGit  git+https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git resetting remote C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> 18 warn addRemoteGit
> 18 warn addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
> 18 warn addRemoteGit     at emitTwo (events.js:106:13)
> 18 warn addRemoteGit     at ChildProcess.emit (events.js:191:7)
> 18 warn addRemoteGit     at maybeClose (internal/child_process.js:877:16)
> 18 warn addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 18 warn addRemoteGit   killed: false,
> 18 warn addRemoteGit   code: 1,
> 18 warn addRemoteGit   signal: null,
> 18 warn addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
> 19 info resetRemote resetting C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322 for git+https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git
> 20 silly gentlyRm C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322 is being purged
> 21 verbose gentlyRm don't care about contents; nuking C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322
> 22 silly vacuum-fs purging C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322
> 23 silly vacuum-fs quitting because other entries in C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes
> 24 info git [ 'clone',
> 24 info git   '--template=C:\\Users\\royib\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
> 24 info git   '--mirror',
> 24 info git   'https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git',
> 24 info git   'C:\\Users\\royib\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322' ]
> 25 error git clone --template=C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322: Cloning into bare repository 'C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322'...
> 25 error git clone --template=C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322: fatal: Unable to find remote helper for 'https'
> 26 silly fetchPackageMetaData Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322
> 26 silly fetchPackageMetaData Cloning into bare repository 'C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322'...
> 26 silly fetchPackageMetaData fatal: Unable to find remote helper for 'https'
> 26 silly fetchPackageMetaData
> 26 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:206:12)
> 26 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
> 26 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
> 26 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:877:16)
> 26 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 26 silly fetchPackageMetaData  error for https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git { Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322
> 26 silly fetchPackageMetaData Cloning into bare repository 'C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322'...
> 26 silly fetchPackageMetaData fatal: Unable to find remote helper for 'https'
> 26 silly fetchPackageMetaData
> 26 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:206:12)
> 26 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
> 26 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
> 26 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:877:16)
> 26 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 26 silly fetchPackageMetaData   killed: false,
> 26 silly fetchPackageMetaData   code: 128,
> 26 silly fetchPackageMetaData   signal: null,
> 26 silly fetchPackageMetaData   cmd: 'git -c core.longpaths=true clone --template=C:\\Users\\royib\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates --mirror https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git C:\\Users\\royib\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322' }
> 27 silly rollbackFailedOptional Starting
> 28 silly rollbackFailedOptional Finishing
> 29 silly runTopLevelLifecycles Finishing
> 30 silly install printInstalled
> 31 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322
> 31 verbose stack Cloning into bare repository 'C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322'...
> 31 verbose stack fatal: Unable to find remote helper for 'https'
> 31 verbose stack
> 31 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
> 31 verbose stack     at emitTwo (events.js:106:13)
> 31 verbose stack     at ChildProcess.emit (events.js:191:7)
> 31 verbose stack     at maybeClose (internal/child_process.js:877:16)
> 31 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 32 verbose cwd D:\Projects\trt\client\node_modules
> 33 error Windows_NT 10.0.14393
> 34 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git" "--save"
> 35 error node v6.9.5
> 36 error npm  v3.10.10
> 37 error code 128
> 38 error Command failed: git -c core.longpaths=true clone --template=C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322
> 38 error Cloning into bare repository 'C:\Users\royib\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ionic-team-cordova-plugin-wkwebview-engine-git-ae2e0322'...
> 38 error fatal: Unable to find remote helper for 'https'
> 39 error If you need help, you may report this error at:
> 39 error     <https://github.com/npm/npm/issues>
> 40 verbose exit [ 1, true ]
>

**Comment by xlinx69** [comment]
hi , exactly the same for me .. stuck for days

**Comment by mokci** [comment]
me too

**Comment by danielehrhardt** [comment]
```
 Discovered plugin "cordova-plugin-wkwebview-engine" in config.xml. Adding it to the project
        Failed to restore plugin "cordova-plugin-wkwebview-engine" from config.xml. You might need to try adding it
        again. Error: Failed to fetch plugin
        cordova-plugin-wkwebview-engine@git+https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git via
        registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! Error while executing:
        npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t
        https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git
        npm ERR!
        npm ERR! fatal: Unable to find remote helper for 'https'
        npm ERR!
        npm ERR! exited with error code: 128
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Daniel\AppData\Roaming\npm-cache\_logs\2017-07-24T20_16_32_150Z-debug.log
        --save flag or autosave detected
        Saving android@~6.2.3 into config.xml file ...
```

**Comment by patwaswapnil** [comment]
`cordova plugin add https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git --save` worked for me.

**Comment by royibernthal** [comment]
`cordova plugin add https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git --save` worked for me too.

However `ionic cordova plugin add https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git --save` is still a bug that needs to be fixed.

**Comment by reverie-ss** [comment]
**First add, SSH key to your GitHub account.**
To add SSH key, 

- Follow these guidelines : [Adding New SSH key](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account)

Then run, `cordova plugin add https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git --save`
Make sure you run the above code in GitBash. Sometimes the error persists in other CLI.

**Comment by royibernthal** [comment]
The problem is with **ionic** cordova plugin

**Comment by JefferE** [comment]
I agree. It is the Ionic version of this plugin installer that is the problem. It may be the plugins fault for not having a proper package.json file but the ionic command obviously does not handle that issue as well as the native cordova command.

This is broken:

`ionic cordova plugin add ...`

This works:

`cordova plugin add ...`

I have found this to be the case on a few other plugins as well ([inapppurchase](https://github.com/rsanchez-forks/cordova-plugin-inapppurchase.git) for one).
